// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ValhallaManagement.Infrastructure.Data;

#nullable disable

namespace ValhallaManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApDbContext))]
    [Migration("20240924030717_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ValhallaManagement.Core.Entities.Vikingo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArmaFavorita")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BatallasGanadas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CausaMuerteGloriosa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Clasificacion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NivelHonor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ValhallaPoints")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Vikingos");
                });
#pragma warning restore 612, 618
        }
    }
}
